version: '3.8'

services:
  nats:
    image: nats:latest
    container_name: nats-server
    ports:
      - "4222:4222"
      - "8222:8222"
    restart: always

  redis:
    image: redis:alpine
    container_name: redis-local
    command: redis-server --appendonly yes # Bật AOF để lưu dữ liệu liên tục
    ports:
      - "6379:6379"
    volumes:
      - redis_local_data:/data # Ánh xạ volume để không mất dữ liệu
    restart: always

volumes:
  redis_local_data: