# =========================================================================================
# 📚 TỪ ĐIỂN CÁC TỪ KHÓA CẤU HÌNH TRONG NGINX (CHEAT SHEET)
# =========================================================================================
# 1. server            : Khai báo một máy chủ ảo (tưởng tượng như 1 quầy lễ tân). Bạn có thể có nhiều block server.
# 2. listen            : Khai báo cổng mà Nginx sẽ đứng gác (VD: listen 80; cho HTTP, listen 443; cho HTTPS). LƯU Ý: Nginx dùng khoảng trắng, KHÔNG dùng dấu hai chấm (:) ở đây.
# 3. server_name       : Khai báo tên miền. (VD: server_name api.myapp.com; hoặc localhost).
# 4. location          : Xác định các quy tắc xử lý khi khách truy cập vào một đường dẫn cụ thể (VD: location / { ... }).
# 5. proxy_pass        : Lệnh quan trọng nhất của Reverse Proxy! Nó đẩy khách (request) từ Nginx vào đường link của container bên trong (VD: proxy_pass http://tên-container:cổng;).
# 6. proxy_set_header  : Gửi kèm thêm thông tin của khách (như IP thật, tên miền) cho Backend biết. 
#                        (VD: proxy_set_header Host $host; proxy_set_header X-Real-IP $remote_addr;)
# 7. root              : Dùng khi cấu hình cho Frontend, chỉ định thư mục chứa file HTML/CSS/JS (VD: root /usr/share/nginx/html;).
# 8. index             : Chỉ định file mặc định sẽ được tải khi vào web (VD: index index.html;).
# =========================================================================================

server {
    #Cổng mặc định của HTTP tôi sẽ cấu hình nginx lắng nghe ở cổng này
    listen 80;

 #Xử lý khi người dùng truy cập vào http://localhost/
 # Dấu / đại diện cho các đường link

    # 1. Luồng Giao diện (Frontend): Ai vào trang chủ (/) thì trả về giao diện React
    location / {
        # Trỏ tới thư mục chứa code tĩnh của React bên trong máy ảo Nginx
        root /usr/share/nginx/html;
        index index.html;
        
        # Dòng này cực kỳ quan trọng đối với React Router (Tránh lỗi 404 khi f5 trang)
        try_files $uri $uri/ /index.html;
    }

     # 2. Luồng Dữ liệu (Backend): Ai gọi link có chữ /api thì đẩy xuống API Gateway
    location /api/ {
        proxy_pass http://api-gateway:3000;
        
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }


    # Khai báo tên miền của web
    server_name api.mycompany.local;

    # Cho phép người dùng tải lên file tối đa 50 Megabytes
    client_max_body_size 50M;
    
    # Tắt thông tin phiên bản Nginx trên Response Headers (Để tăng cường bảo mật)
    server_tokens off;

    # lằng nghe cổng 433 cho https có chứa ttheem các chức năng bảo mật
    # listen 443 ssl; cái này xin 

   

}
